package main

type TestSdOceanenginePlan struct {
	Active                            int64  `json:"active"`
	ActiveCost                        int64  `json:"active_cost"`
	ActivePayCost                     int64  `json:"active_pay_cost"`
	ActivePayRate                     int64  `json:"active_pay_rate"`
	ActiveRate                        int64  `json:"active_rate"`
	ActiveRegisterCost                int64  `json:"active_register_cost"`
	ActiveRegisterRate                int64  `json:"active_register_rate"`
	AdID                              int64  `json:"ad_id"`
	AdName                            int64  `json:"ad_name"`
	AdvancedCreativeCounselClick      int64  `json:"advanced_creative_counsel_click"`
	AdvancedCreativeCouponAddition    int64  `json:"advanced_creative_coupon_addition"`
	AdvancedCreativeFormClick         int64  `json:"advanced_creative_form_click"`
	AdvancedCreativeFormSubmit        int64  `json:"advanced_creative_form_submit"`
	AdvancedCreativePhoneClick        int64  `json:"advanced_creative_phone_click"`
	AttributionActivePay7dPerCount    int64  `json:"attribution_active_pay_7d_per_count"`
	AttributionConvert                int64  `json:"attribution_convert"`
	AttributionConvertCost            int64  `json:"attribution_convert_cost"`
	AttributionDeepConvert            int64  `json:"attribution_deep_convert"`
	AttributionDeepConvertCost        int64  `json:"attribution_deep_convert_cost"`
	AttributionGamePay7dCost          int64  `json:"attribution_game_pay_7d_cost"`
	AttributionGamePay7dCount         int64  `json:"attribution_game_pay_7d_count"`
	AttributionNextDayOpenCnt         int64  `json:"attribution_next_day_open_cnt"`
	AttributionNextDayOpenCost        int64  `json:"attribution_next_day_open_cost"`
	AttributionNextDayOpenRate        int64  `json:"attribution_next_day_open_rate"`
	AttributionWechatFirstPay30dCost  int64  `json:"attribution_wechat_first_pay_30d_cost"`
	AttributionWechatFirstPay30dCount int64  `json:"attribution_wechat_first_pay_30d_count"`
	AttributionWechatFirstPay30dRate  int64  `json:"attribution_wechat_first_pay_30d_rate"`
	AttributionWechatLogin30dCost     int64  `json:"attribution_wechat_login_30d_cost"`
	AttributionWechatLogin30dCount    int64  `json:"attribution_wechat_login_30d_count"`
	AttributionWechatPay30dAmount     int64  `json:"attribution_wechat_pay_30d_amount"`
	AttributionWechatPay30dRoi        int64  `json:"attribution_wechat_pay_30d_roi"`
	AveragePlayTimePerPlay            int64  `json:"average_play_time_per_play"`
	AvgClickCost                      int64  `json:"avg_click_cost"`
	AvgShowCost                       int64  `json:"avg_show_cost"`
	Button                            int64  `json:"button"`
	CampaignID                        int64  `json:"campaign_id"`
	CampaignName                      int64  `json:"campaign_name"`
	CardShow                          int64  `json:"card_show"`
	Click                             int64  `json:"click"`
	ClickCallDy                       int64  `json:"click_call_dy"`
	ClickDownload                     int64  `json:"click_download"`
	ClickInstall                      int64  `json:"click_install"`
	ClickLandingPage                  int64  `json:"click_landing_page"`
	ClickShopwindow                   int64  `json:"click_shopwindow"`
	ClickWebsite                      int64  `json:"click_website"`
	Comment                           int64  `json:"comment"`
	Consult                           int64  `json:"consult"`
	ConsultEffective                  int64  `json:"consult_effective"`
	Convert                           int64  `json:"convert"`
	ConvertCost                       int64  `json:"convert_cost"`
	ConvertRate                       int64  `json:"convert_rate"`
	Cost                              int64  `json:"cost"`
	Coupon                            int64  `json:"coupon"`
	CouponSinglePage                  int64  `json:"coupon_single_page"`
	Ctr                               int64  `json:"ctr"`
	DeepConvert                       int64  `json:"deep_convert"`
	DeepConvertCost                   int64  `json:"deep_convert_cost"`
	DeepConvertRate                   int64  `json:"deep_convert_rate"`
	Download                          int64  `json:"download"`
	DownloadFinish                    int64  `json:"download_finish"`
	DownloadFinishCost                int64  `json:"download_finish_cost"`
	DownloadFinishRate                int64  `json:"download_finish_rate"`
	DownloadStart                     int64  `json:"download_start"`
	DownloadStartCost                 int64  `json:"download_start_cost"`
	DownloadStartRate                 int64  `json:"download_start_rate"`
	Follow                            int64  `json:"follow"`
	Form                              int64  `json:"form"`
	GameAddiction                     int64  `json:"game_addiction"`
	GameAddictionCost                 int64  `json:"game_addiction_cost"`
	GameAddictionRate                 int64  `json:"game_addiction_rate"`
	GamePayCost                       int64  `json:"game_pay_cost"`
	GamePayCount                      int64  `json:"game_pay_count"`
	HomeVisited                       int64  `json:"home_visited"`
	ID                                int64  `json:"id"`
	IesChallengeClick                 int64  `json:"ies_challenge_click"`
	IesMusicClick                     int64  `json:"ies_music_click"`
	InAppCart                         int64  `json:"in_app_cart"`
	InAppDetailUv                     int64  `json:"in_app_detail_uv"`
	InAppOrder                        int64  `json:"in_app_order"`
	InAppPay                          int64  `json:"in_app_pay"`
	InAppUv                           int64  `json:"in_app_uv"`
	InstallFinish                     int64  `json:"install_finish"`
	InstallFinishCost                 int64  `json:"install_finish_cost"`
	InstallFinishRate                 int64  `json:"install_finish_rate"`
	Like                              int64  `json:"like"`
	LiveFansClubJoinCnt               int64  `json:"live_fans_club_join_cnt"`
	LiveWatchOneMinuteCount           int64  `json:"live_watch_one_minute_count"`
	LoanCompletion                    int64  `json:"loan_completion"`
	LoanCompletionCost                int64  `json:"loan_completion_cost"`
	LoanCompletionRate                int64  `json:"loan_completion_rate"`
	LoanCredit                        int64  `json:"loan_credit"`
	LoanCreditCost                    int64  `json:"loan_credit_cost"`
	LoanCreditRate                    int64  `json:"loan_credit_rate"`
	LocationClick                     int64  `json:"location_click"`
	Lottery                           int64  `json:"lottery"`
	LubanLiveClickProductCnt          int64  `json:"luban_live_click_product_cnt"`
	LubanLiveCommentCnt               int64  `json:"luban_live_comment_cnt"`
	LubanLiveEnterCnt                 int64  `json:"luban_live_enter_cnt"`
	LubanLiveFollowCnt                int64  `json:"luban_live_follow_cnt"`
	LubanLiveGiftAmount               int64  `json:"luban_live_gift_amount"`
	LubanLiveGiftCnt                  int64  `json:"luban_live_gift_cnt"`
	LubanLivePayOrderCount            int64  `json:"luban_live_pay_order_count"`
	LubanLivePayOrderStatCost         int64  `json:"luban_live_pay_order_stat_cost"`
	LubanLiveShareCnt                 int64  `json:"luban_live_share_cnt"`
	LubanLiveSlidecartClickCnt        int64  `json:"luban_live_slidecart_click_cnt"`
	LubanOrderCnt                     int64  `json:"luban_order_cnt"`
	LubanOrderRoi                     int64  `json:"luban_order_roi"`
	LubanOrderStatAmount              int64  `json:"luban_order_stat_amount"`
	MapSearch                         int64  `json:"map_search"`
	Message                           int64  `json:"message"`
	MessageAction                     int64  `json:"message_action"`
	NextDayOpen                       int64  `json:"next_day_open"`
	NextDayOpenCost                   int64  `json:"next_day_open_cost"`
	NextDayOpenRate                   int64  `json:"next_day_open_rate"`
	PayCount                          int64  `json:"pay_count"`
	Phone                             int64  `json:"phone"`
	PhoneConfirm                      int64  `json:"phone_confirm"`
	PhoneConnect                      int64  `json:"phone_connect"`
	PhoneEffective                    int64  `json:"phone_effective"`
	Play100FeedBreak                  int64  `json:"play_100_feed_break"`
	Play25FeedBreak                   int64  `json:"play_25_feed_break"`
	Play50FeedBreak                   int64  `json:"play_50_feed_break"`
	Play75FeedBreak                   int64  `json:"play_75_feed_break"`
	PlayDurationSum                   int64  `json:"play_duration_sum"`
	PlayOverRate                      int64  `json:"play_over_rate"`
	PoiAddressClick                   int64  `json:"poi_address_click"`
	PoiCollect                        int64  `json:"poi_collect"`
	PreLoanCredit                     int64  `json:"pre_loan_credit"`
	PreLoanCreditCost                 int64  `json:"pre_loan_credit_cost"`
	Qq                                int64  `json:"qq"`
	Redirect                          int64  `json:"redirect"`
	RedirectToShop                    int64  `json:"redirect_to_shop"`
	Register                          int64  `json:"register"`
	Share                             int64  `json:"share"`
	Shopping                          int64  `json:"shopping"`
	Show                              int64  `json:"show"`
	StatDatetime                      string `json:"stat_datetime"`
	TotalPlay                         int64  `json:"total_play"`
	ValidPlay                         int64  `json:"valid_play"`
	ValidPlayCost                     int64  `json:"valid_play_cost"`
	ValidPlayRate                     int64  `json:"valid_play_rate"`
	View                              int64  `json:"view"`
	Vote                              int64  `json:"vote"`
	Wechat                            int64  `json:"wechat"`
	WechatFirstPayCost                int64  `json:"wechat_first_pay_cost"`
	WechatFirstPayCount               int64  `json:"wechat_first_pay_count"`
	WechatFirstPayRate                int64  `json:"wechat_first_pay_rate"`
	WechatLoginCost                   int64  `json:"wechat_login_cost"`
	WechatLoginCount                  int64  `json:"wechat_login_count"`
	WechatPayAmount                   int64  `json:"wechat_pay_amount"`
	WifiPlay                          int64  `json:"wifi_play"`
	WifiPlayRate                      int64  `json:"wifi_play_rate"`
}

type SdCronJob struct {
	Uid        string `json:"uid"`
	Url        string `json:"url"`
	JobId      string `json:"job_id"`
	JobName    string `json:"job_name"`
	GroupId    string `json:"group_id"`
	GroupName  string `json:"group_name"`
	Status     string `json:"status"`
	ResultMsg  string `json:"result_msg"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	ServerIp   string `json:"server_ip"`
	OptionUser string `json:"option_user"`
}


type SlotList struct {
	Uid        string `json:"uid"`
	Url        string `json:"url"`
	JobId      string `json:"job_id"`
	JobName    string `json:"job_name"`
	GroupId    string `json:"group_id"`
	GroupName  string `json:"group_name"`
	Status     string `json:"status"`
	ResultMsg  string `json:"result_msg"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	ServerIp   string `json:"server_ip"`
	OptionUser string `json:"option_user"`
}




